### ISSUE TITLE
bug(orderedReducer): DOCUMENT_MODIFIED action doesn't change index in the "ordered" array

### ISSUE THREAD

**Issue by vnikanorov** [prescottprue/redux-firestore#230]
**What is the current behavior?**
DOCUMENT_MODIFIED action doesn't change index in the "ordered" array
![image](https://user-images.githubusercontent.com/32862092/62626338-d20a4280-b92f-11e9-9165-74a755b3ba52.png)
![image](https://user-images.githubusercontent.com/32862092/62626392-f6feb580-b92f-11e9-9d8a-d53ec7ec16ca.png)

"-L_MnT5FxK..." still has 1 index instead of 0.

**What is the expected behavior?**
I have a query (firestoreConnect from the react-redux-firebase):
```
{
        collection: COLLECTION_PATH,
        where: [
          ['deleted', '==', false],
        ],
        orderBy: ['timeLastUpdatedAt', 'desc'],
}
```
When I update the document, timeLastUpdatedAt updated too, but the order in the store doesn't change.
However, the payload contains the "ordered: {oldIndex, newIndex}".

I want to get a sorted collection when I update a document

**Which version of redux-firestore are you using? What about other dependencies?**
react-redux-firebase: 2.3.0
redux-firestore: 0.6.4

**Which environments/browsers are affected by this issue? Did this work in previous versions or setups?**
Chrome, Localhost

**Comment by prescottprue** [comment]
Fix released in [v0.9.0](https://github.com/prescottprue/redux-firestore/releases/tag/v0.9.0). Thanks for reporting.

**Comment by sintylapse** [comment]
@vnikanorov do you have your issue fixed? it seems it's not fixed for me, though I updated redux-firestore
cc: @prescottprue

**Comment by prescottprue** [comment]
@sintylapse [This test was added to confirm](https://github.com/prescottprue/redux-firestore/commit/321578336bf907e06cbbe4c9c271321b04bd4aee#diff-f44bcac9ab941d8922fc77a9ef12c26d) that this type of update correctly updates the store, so surprised to hear that it is happening to you. Maybe there is another case we are missing?

Could you provide an example that reproduces the issue to confirm we are referring to the same thing?

**Comment by sintylapse** [comment]
@prescottprue I connect to Firestore like this
```
firestoreConnect([
    {
        collection: 'emotions',
        orderBy: ['updateDate', 'desc'],
    },
]),
```
then I open the screen with collection and collections are ordered by updateDate (desc). Then if I update a record
```
newRecord.updateDate = new Date()

firestore
    .collection('emotions')
    .doc(record.id)
    .update({ ...newRecord })
```
all content of the record will be updated, but not the order

<img width="956" alt="Screen Shot 2019-09-18 at 15 39 14" src="https://user-images.githubusercontent.com/12295016/65154140-3fc78500-da2b-11e9-8078-5297a1adc057.png">

If I go back and open screen again, everything is ordered fine again.

<img width="347" alt="Screen Shot 2019-09-18 at 15 46 22" src="https://user-images.githubusercontent.com/12295016/65154315-93d26980-da2b-11e9-9566-89eb0ab8bfb5.png">

**Comment by sintylapse** [comment]
Actually order works fine if I use
```
firestoreConnect([
    {
        collection: 'emotions',
        orderBy: 'updateDate',
    },
]),
```
so, the problem might be in desc, or using array on orderBy @prescottprue

**Comment by prescottprue** [comment]
@sintylapse Great to know, thanks for reporting. We should open a new issue to track fixing what you mentioned (i.e. doesn't work with desc or using an array on `orderBy`). Would you mind opening it?

**Comment by sintylapse** [comment]
@prescottprue sure https://github.com/prescottprue/redux-firestore/issues/239
