### ISSUE TITLE
bug(reducers): multiple subcollections on same parent collection causes invalid merge

### ISSUE THREAD

**Issue by diagramatics** [prescottprue/redux-firestore#34]
Here's the scenario. This is React code with a router and I have two components on two different pages doing:

```js
  firestoreConnect([
    { collection: 'group', doc: 'uJH3akkXRkje3ruPZ7au' },
    {
      collection: 'group',
      doc: 'uJH3akkXRkje3ruPZ7au',
      subcollections: [{ collection: 'objects' }],
    },
  ]),
```

And the other one doing
```js
firestoreConnect(['group'])
```

Whenever I go from the first component to the second component,`firestoreConnect` on `group` would shallow merge the specific doc and removing the subcollection information stored in there, both on `dataReducer` and `orderedReducer`.

**Comment by prescottprue** [comment]
@diagramatics This should be fixed by [this PR for `v0.2.1`](https://github.com/prescottprue/redux-firestore/pulls), which has not yet been merged or released. Could you give it a try [using `npm link`](docs.react-redux-firebase.com/history/v2.0.0/docs/contributing.html#npm-linking) to confirm it fixes things for you?

**Comment by diagramatics** [comment]
Yeah I was using 0.2.1 to verify this still happens in the new version, and I believe it still does.

**Comment by prescottprue** [comment]
@diagramatics Good to know. If you need a solution in the meantime you can use `storeAs` to place the data in different locations of redux and merge the data by hand.

**Comment by Klabauterman** [comment]
I have the same issue even in 0.2.5. It is also a problem if you have two subcollections in the same parent document. Both are updating the parent document and the second subcollection update removes the data of the first one from the store-state. Maybe I could use storeAs as a workaround, but I think that is not a good solution.

**Comment by prescottprue** [comment]
Fixed as part of [`0.3.1` release](https://github.com/prescottprue/redux-firestore/releases/tag/v0.3.1).

Reach out if things are working as expected. Thanks for reporting!
