### ISSUE TITLE
bug(reducer): delete does not remove item from data state

### ISSUE THREAD

**Issue by jeandavid** [prescottprue/redux-firestore#45]
firestore.delete correctly removes the item from the firestore database but not from redux store. ( I do have a listener, firestore.add works great)

**Comment by prescottprue** [comment]
@jeandavid Are you using the newest version?

Does it remove from `firestore.ordered`? or is neither updating for you?

**Comment by jeandavid** [comment]
I am using the newest 0.2.5 version. Deleted item is removed from firestore.ordered but not from firestore.data

**Comment by prescottprue** [comment]
@jeandavid This should be fixed as part of [the `v0.3.0` release](https://github.com/prescottprue/redux-firestore/releases/tag/v0.3.0). 

Items within data are being set to `null` when `DELETE_SUCCESS` actions are dispatched. There is also a matching tests for it.

Thanks for reporting!

**Comment by komasoftware** [comment]
I am at the latest version 0.3.2 and I am still seeing this issue.

When I delete a document from firestore using the console, my LISTENER_REPONSE is fired off but the deleted document is still present as state under 'firestore.data' It is only removed from 'firestore.ordered'.

Am I missing something here ?

**Comment by prescottprue** [comment]
@komasoftware Though I don't like this answer for now: `v0.3.1` should work for you, but the change needed to be revered in `v0.3.2`.

Currently with how the reducer works, either merging can be enabled to preserve sub-collections or it can be off to make sure that listener responses that remove properties still work.

Going to reopen this until we have a better solution, thanks for the reminder.

**Comment by prescottprue** [comment]
v0.4.0 was released which correctly updates ordered state if either a collection or document listener is attached. Thanks for reporting.

**Comment by komasoftware** [comment]
Verified ! Thx !

![selection_855](https://user-images.githubusercontent.com/482152/38861063-ecd5b67e-4231-11e8-8c85-cd9ce5c93631.jpg)

**Comment by gino-m** [comment]
Still experiencing this on 0.5.7.

**Comment by prescottprue** [comment]
@ivawzh and others that have been experiencing the issue:

There have been a number of issues reported relating to how subcollections are stored. To address these, I have [started the v1.0.0 Roadmap doc](https://github.com/prescottprue/redux-firestore/wiki/v1.0.0-Roadmap) which includes notes about the current plans for the new state pattern.

**Comment by rscotten** [comment]
I had this problem too, but it turns out it's because I was doing a document delete inside a *transaction* instead of deleting that document directly.  If deleting directly, redux-firestore works as expected.

The problem is that when listening on a collection, deleting a document from that collection inside a transaction correctly removes the document from the `state.firestore.ordered['storeAs']` but it does not remove that document from `state.firestore.data['storeAs']`.  

This is because the previous data is being merged with the current data using `lodash.assign` in `src/reducers/dataReducer.js` on line 63.  

Merging this way works for *updating* document data, but the *deleted* documents cannot get removed this way.  

The easy solution is to just not delete inside transactions if you're relying on `state.firestore.data['storeAs']` for whether a document exists or not.  Otherwise, maybe @prescottprue would consider an alternative approach to merging new and previous data for the listener.  Perhaps merging is unhelpful here, although I do see a test for this specific data merge.

**Comment by rscotten** [comment]
@prescottprue, Since a LISTENER_RESPONSE action does not merge the new and existing data for `ordered`, `queries.data`, and `composite`, it's inconsistent for it to happen for `data` in `src/reducers/dataReducer`.  It's also unexpected and inconvenient.  

Is it necessary or can we remove the merge and just use the new data?

**Comment by prescottprue** [comment]
@rscotten We can remove the merge and just use the new data - feel free to open a PR.

**Comment by mozamarius** [comment]
Any updates on this?

**Comment by rscotten** [comment]
I can submit a PR this weekend.

**Comment by mozamarius** [comment]
Any workaround on this ? I can't use ordered because of populate.

**Comment by rscotten** [comment]
Sorry I couldn't get to this yesterday.  I'm working on it right now.

**Comment by rscotten** [comment]
@mozamarius @prescottprue PR #218

**Comment by mozamarius** [comment]
@prescottprue @rscotten 
Some strange behavior, if i have more then 2, it doesn't remove it from data, it's set to null.

![bug](https://user-images.githubusercontent.com/17565578/57772785-0ef2de80-771f-11e9-9b9e-7de7ff2f4a7e.png)

But if i have 2 or less in the list, works fine.

**Comment by rscotten** [comment]
@mozamarius Looking into this right now

**Comment by rscotten** [comment]
@mozamarius  I just wrote a test for deleting 1 document from a collection of 4 documents and I don't get the docId with a null value.  So 

1. Please post the code you're using to delete the document.
2. If you have the Redux Dev Tools Chrome extension (you should), please post a screenshot of the redux actions for the delete operation.

**Comment by rscotten** [comment]
@mozamarius I see what the problem is: when deleting a document, the `DOCUMENT_REMOVED` action is fired and not the `LISTENER_RESPONSE` action.  This is why the data collection document value gets set to `null` rather than removed altogether.

@prescottprue When deleting a document from a collection being listened on, what was the intent behind setting a document to `null` instead of removing that document from the `data['collection']`?  Since the document gets removed from `ordered['collection']`, `composite['collection']`, and `queries['query].data`, it seems inconsistent and unexpected to persist the document key and set it's value to `null`.  Can we just remove it from the `data['collection']` instead?

**Comment by prescottprue** [comment]
@rscotten The reason for setting `null` instead of removing the document was to indicate that the data is loaded, but empty. When the value is `undefined` it could mean that the data hasn't loaded yet.

**Comment by Wgil** [comment]
@prescottprue Does that imply that whenever I want to use `firestore.data.key[id]` I have always to check if the value it's not `null`? I think it is more natural to think that whatever objects are inside `data.key` do actually contain something like it happens now with `firestore.ordered`.

Is there any chance we can consider managing loading and empty state in a diferent key other than `data`?

**Comment by prescottprue** [comment]
@Wgil Would you mind opening a new issue to request the feature? It might be the type of thing that we switch to or put into another piece of state as you mentioned, so it would be good to have a place to discuss it.

**Comment by Wgil** [comment]
@prescottprue Sure, I'll.

It seems `@@reduxFirestore/DOCUMENT_MODIFIED` it's not updating `ordered` key properly.

![Screen Shot 2019-08-08 at 10 15 18 AM](https://user-images.githubusercontent.com/12855914/62710560-8609dd00-b9c5-11e9-84c6-8dd1b588c0c5.png)

**Comment by Wgil** [comment]
This query is also broken on 0.8.0:

```
getUsers: ({ firestore }) => usersIdsArray => {
      return usersIdsArray.map(userId =>
        firestore.get({
          collection: 'users',
          where: ['id', '==', userId]
        })
      )
    }
```

![image](https://user-images.githubusercontent.com/12855914/62744671-a497c480-ba15-11e9-925a-56721701314f.png)

It's working fine on 0.7.0

**Comment by prescottprue** [comment]
@Wgil lets open new issues for both cases so we can track tackling each one. Thanks for reporting!

**Comment by Anne-Anq** [comment]
> This query is also broken on 0.8.0:
> 
> ```
> getUsers: ({ firestore }) => usersIdsArray => {
>       return usersIdsArray.map(userId =>
>         firestore.get({
>           collection: 'users',
>           where: ['id', '==', userId]
>         })
>       )
>     }
> ```
> 
> ![image](https://user-images.githubusercontent.com/12855914/62744671-a497c480-ba15-11e9-925a-56721701314f.png)
> 
> It's working fine on 0.7.0

Hi,
We are still facing that issue with 0.11.0:
The query works great on 0.7.0, all the queried users are merged in firestore.data.users, but in 0.11.0 or 0.8.0 the user documents queried one after another replace one another instead of being just added to the existing doc

**Comment by prescottprue** [comment]
@Anne-Anq can you open a new issue describing your issue with reproduction steps so we can get to the bottom of it? You should be able to use `storeAs` as a workaround for now since that will not store data under users - you could also try using Firebase's new `in` query:

```js
firestore.get({
  collection: 'users',
  where: ['id', 'in', usersIdsArray]
})
```

**Comment by Anne-Anq** [comment]
Hi Scott!
Thank you so much for your answer.

Firebase new query `in` works great indeed, thanks.  I use this query with
`storeAs:'users'` and I am able to fetch user X-Y-Z at once and I find them
all  in my data.users .

However if I re-use the same query  to fetch users A-B-C later on, it will
overwrite Z-Y-Z. Meaning, instead of having X-Y-Z-A-B-C in data.users, I
have only A-B-C...

Is this by design or is this a bug?

We found a workaround so it is no longer a problem for us, but let me
know if you still want me to open an issue for it.

Again thanks for your help, and for the great lib
